# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='url')),
                ('content', models.TextField(max_length=100000, null=True, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
                'ordering': ['-created_at'],
            },
        ),
    ]
