# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackmds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-created_at'], 'verbose_name': 'Archive', 'verbose_name_plural': 'Archives'},
        ),
    ]
