# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackmds', '0003_auto_20171023_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='content',
            field=models.TextField(max_length=100000, null=True, verbose_name='content'),
        ),
    ]
